### GET request to example server
GRPC localhost:2002/bosca.dc.DistributedCache/CreateCache
Content-Type: application/json

{
  "name": "test",
  "max_capacity": 1000
}

###
GRPC localhost:2002/bosca.dc.DistributedCache/PutValue
Content-Type: application/json

{
  "cache": "test",
  "key": "testkey",
  "value": asdf
}

###
GRPC localhost:2002/bosca.dc.DistributedCache/PutValue
Content-Type: application/json

{
  "cache": "test",
  "key": "testkey1231245125125",
  "value": asdf
}

###
GRPC localhost:2002/bosca.dc.DistributedCache/GetValue
Content-Type: application/json

{
  "cache": "test",
  "key": "testkey"
}

###
GRPC localhost:2001/bosca.dc.DistributedCache/GetValue
Content-Type: application/json

{
  "cache": "test",
  "key": "testkey1231245125125"
}

###
GRPC localhost:2001/bosca.dc.DistributedCache/DeleteValue
Content-Type: application/json

{
  "cache": "test",
  "key": "testkey"
}

###
GRPC localhost:2001/bosca.dc.DistributedCache/SubscribeNotifications
Content-Type: application/json
