resources:
  - statefulset.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: analytics-backend-env
    literals:
      - BATCHES_DIR=/data/batches
      - PENDING_OBJECTS_DIR=/data/pending
      - TEMP_DIR=/data/temp
      - OTLP_TRACE_ENDPOINT=http://otel-collector.bosca.svc.cluster.local:4318/v1/traces
      - OTLP_METRICS_ENDPOINT=http://otel-collector.bosca.svc.cluster.local:4318/v1/metrics
