[workspace]
resolver = "2"
members = [
    "workspace/core/migrations",
    "workspace/core/server",
    "workspace/core/analytics",
    "workspace/core/util/telemetry",
    "workspace/core/util/database",
]
