[workspace]
resolver = "2"
members = [
    "workspace/core/migrations",
    "workspace/core/server",
    "workspace/core/analytics",
    "workspace/core/util/database",
    "workspace/core/dc",
    "workspace/core/dc-client",
]
