[workspace]
resolver = "2"
members = [
    "workspace/migrations",
    "workspace/server",
    "workspace/analytics",
    "workspace/front",
    "workspace/util/telemetry",
    "workspace/graphql-clients/client-generator",
]
