FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

# Copy package.json and your lockfile, here we add pnpm-lock.yaml for illustration
COPY ./installer .
COPY ./graphql .

# Install dependencies
RUN pnpm i

# Copy the entire project
COPY . ./

CMD ["node", "--experimental-strip-types", "installer/main.ts"]
