FROM debian:bookworm-slim

RUN apt update && apt install -y ffmpeg

COPY workspace/runners/kotlin/runner/build/native/nativeCompile/* /

EXPOSE 8000
CMD ["./bosca-runner", "run", "-D", "java.io.tmpdir", "/tmp/bosca"]