include:
  # This includes services like database, storage, etc
  - services/docker-compose.yaml

services:
  database-migration:
    image: ghcr.io/sowers-io/bosca/database-migrations:latest
    platform: linux/amd64
    pull_policy: always
    environment:
      DATABASE_URL: postgresql://bosca:bosca@postgres:5432/bosca
    networks:
      - boscanet
    depends_on:
      postgres:
        condition: service_healthy

  server:
    image: ghcr.io/sowers-io/bosca/server:latest
    platform: linux/amd64
    environment:
      BOSCA_URL_PREFIX: http://server:8000
      DATABASE_URL: postgres://bosca:bosca@postgres:5432/bosca
      REDIS_JOBS_QUEUE_URL: redis://dragonfly:6379
      REDIS_NOTIFIER_PUBSUB_URL: redis://dragonfly:6379
      JWT_AUDIENCE: bosca.io
      JWT_ISSUER: bosca-graphql
      JWT_SECRET: bosca1234*
      SEARCH_KEY: p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M
      SEARCH_URL: http://meilisearch:7700
      STORAGE: s3
      AWS_BUCKET: bosca
      AWS_FORCE_PATH_STYLE: 'true'
      AWS_ENDPOINT: http://minio:9010
      AWS_ACCESS_KEY_ID: 67fO5gFs6BuksBrh6rMp
      AWS_SECRET_ACCESS_KEY: eV4rlwomvXsM19CXorOTb5uYaFLeNXsPLKx5Uxdm
      AWS_ALLOW_HTTP: true
    ports:
      - '8000:8000'
    restart: always
    networks:
      - boscanet
    depends_on:
      database-migration:
        condition: service_started
      postgres:
        condition: service_healthy
