FROM gcr.io/distroless/cc-debian12

COPY examples/blog/configuration /blog
COPY workspace/runners/kotlin/runner/build/native/nativeCompile/* /

CMD ["./bosca-runner", "install", "--directory", "/blog"]