FROM debian:bookworm-slim

RUN apt update && apt install -y zip unzip curl build-essential zlib1g-dev ffmpeg
RUN curl -s "https://get.sdkman.io" | bash

RUN bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install java 24.0.1-graalce"
ENV JAVA_HOME=/root/.sdkman/candidates/java/current

#COPY workspace/runners/kotlin/runner/build/native/nativeCompile/* /
COPY workspace/runners/kotlin/runner/build/distributions/* /
RUN tar xf runner-1.0-SNAPSHOT.tar && mv runner-1.0-SNAPSHOT runner

COPY examples/blog/configuration /blog

CMD ["./runner/bin/runner", "install", "--directory", "/blog"]