include:
  # This includes services like database, storage, etc
  - services/docker-compose.yaml

services:
  database-migration:
    image: ghcr.io/sowers-io/bosca/database-migrations:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://bosca:bosca@postgres:5432/bosca
    networks:
      - boscanet
    depends_on:
      postgres:
        condition: service_healthy

  analytics:
    image: ghcr.io/sowers-io/bosca/analytics:latest
    platform: linux/amd64
    environment:
      BOSCA_URL_PREFIX: http://server:8000
      STORAGE: s3
      AWS_BUCKET: bosca
      AWS_FORCE_PATH_STYLE: 'true'
      AWS_ENDPOINT: http://minio:9010
      AWS_ACCESS_KEY_ID: 67fO5gFs6BuksBrh6rMp
      AWS_SECRET_ACCESS_KEY: eV4rlwomvXsM19CXorOTb5uYaFLeNXsPLKx5Uxdm
      AWS_ALLOW_HTTP: true
      POD_IP: 127.0.0.1
    ports:
      - '8009:8009'
    restart: always
    networks:
      - boscanet

  imageprocessor:
    image: ghcr.io/sowers-io/bosca/imageprocessor:latest
    platform: linux/amd64
    environment:
      SUPPORTED_URLS: http://localhost:3001,http://server:8000
    ports:
      - '8003:8003'
    restart: always
    networks:
      - boscanet

  server:
    image: ghcr.io/sowers-io/bosca/server:latest
    platform: linux/amd64
    environment:
      BOSCA_URL_PREFIX: http://server:8000
      DATABASE_URL: postgres://bosca:bosca@postgres:5432/bosca
      NATS_URL: nats1:4222
      REDIS_JOBS_QUEUE_HOST: dragonfly
      REDIS_JOBS_QUEUE_PORT: 6379
      REDIS_NOTIFIER_PUBSUB_HOST: dragonfly
      REDIS_NOTIFIER_PUBSUB_PORT: 6379
      JWT_AUDIENCE: bosca.local
      JWT_ISSUER: bosca.local
      JWT_SECRET: QuujwfwQKbdn2GkV64Ri
      SEARCH_KEY: p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M
      SEARCH_URL: http://meilisearch:7700
      STORAGE: s3
      CACHE_HOST: dc
      CACHE_PORT: 2001
      AWS_BUCKET: bosca
      AWS_FORCE_PATH_STYLE: 'true'
      AWS_ENDPOINT: http://minio:9010
      AWS_ACCESS_KEY_ID: 67fO5gFs6BuksBrh6rMp
      AWS_SECRET_ACCESS_KEY: eV4rlwomvXsM19CXorOTb5uYaFLeNXsPLKx5Uxdm
      AWS_ALLOW_HTTP: true
      CONFIGURATION_SECRET_KEY: changeme
      URL_SECRET_KEY: changeme
    ports:
      - '8000:8000'
    restart: always
    networks:
      - boscanet
    healthcheck:
      test: ["NONE"] # TODO: add something to the image to make this work
      start_period: 3s
    depends_on:
      database-migration:
        condition: service_started
      postgres:
        condition: service_healthy

  runner:
    image: ghcr.io/sowers-io/bosca/kotlin-runner-community-compatibility:latest
#    image: ghcr.io/sowers-io/bosca/kotlin-runner-enterprise-compatibility:latest
    platform: linux/amd64
    environment:
      BOSCA_USERNAME: admin
      BOSCA_PASSWORD: password
      BOSCA_QUEUES: "profiles,10;video,4;media,2;default,10;media-transcription,1;media-upload,5;metadata,200;search-index,100;traits,100;transition,100;ai,10;"
      BOSCA_GRAPHQL_URL: http://server:8000/graphql
      BOSCA_WS_URL: ws://server:8000/ws
      SEARCH_KEY: p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M
      SEARCH_URL: http://meilisearch:7700
      IMAGE_PROCESSOR_URL: http://imageprocessor:8003
    restart: always
    networks:
      - boscanet
    depends_on:
      server:
        condition: service_started

  administration:
    image: ghcr.io/sowers-io/bosca/administration:latest
    platform: linux/amd64
    environment:
      NUXT_GRAPHQL_URL: http://server:8000/graphql
      NUXT_GRAPHQL_WS_URL: ws://server:8000/ws
      NUXT_PUBLIC_GRAPHQL_URL: http://localhost:8000/graphql
      NUXT_PUBLIC_GRAPHQL_WS_URL: ws://localhost:8000/ws
    ports:
      - '3001:3000'
    restart: always
    networks:
      - boscanet

  administration-query-installer:
    image: ghcr.io/sowers-io/bosca/administration-query-installer:latest
    platform: linux/amd64
    environment:
      GRAPHQL_URL: http://server:8000/graphql
      GRAPHQL_USERNAME: admin
      GRAPHQL_PASSWORD: password
    restart: on-failure:1000
    networks:
      - boscanet
    depends_on:
      server:
        condition: service_started

  blog-installer:
    image: ghcr.io/sowers-io/bosca/blog-installer-compatibility:latest
    platform: linux/amd64
    environment:
      BOSCA_GRAPHQL_URL: http://server:8000/graphql
      BOSCA_USERNAME: admin
      BOSCA_PASSWORD: password
    restart: on-failure:1000
    networks:
      - boscanet
    depends_on:
      server:
        condition: service_started

  dc:
    image: ghcr.io/sowers-io/bosca/cache:latest
    platform: linux/amd64
    environment:
      DC_HOST: dc
      DC_PORT: 2001
    restart: always
    networks:
      - boscanet