apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  ports:
    - name: http
      port: 7700
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/name: meilisearch
