apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
  labels:
    app.kubernetes.io/instance: meilisearch
    app.kubernetes.io/name: meilisearch
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: meilisearch
      app.kubernetes.io/name: meilisearch
  serviceName: meilisearch
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: meilisearch
        app.kubernetes.io/name: meilisearch
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: meilisearch-environment
            - secretRef:
                name: meilisearch
          image: getmeili/meilisearch:v1.9.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: meilisearch
          ports:
            - containerPort: 7700
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /meili_data
              name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: tmp
        - name: data
          persistentVolumeClaim:
            claimName: meilisearch
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate