name: Build & Publish Backend and Frontend

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  build-and-publish-administration:
    runs-on: ubuntu-22.04
    env:
      RUNNER_TOOL_CACHE: /toolcache
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          ssh-key: ${{ secrets.READ_SSH_KEY }}
          token: ${{ secrets.PRIVATE_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Administration Image
        uses: docker/build-push-action@v3
        with:
          context: workspace/web/administration
          file: Dockerfile-administration
          push: true
          build-args: |
            "VAR_NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}"
          tags: |
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration:latest
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration:${{ github.sha }}
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration:${{ github.ref_name }}
      - name: Build and Publish Administration Query Installer Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-administration-query-installer
          push: true
          tags: |
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration-query-installer:latest
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration-query-installer:${{ github.sha }}
            ${{ secrets.IMAGE_PREFIX }}/bosca/administration-query-installer:${{ github.ref_name }}
