configurations:
  - key: openai
    public: false
    description: OpenAI
    value:
      key:
        env.variable: OPENAI_KEY

  - key: ollama
    public: false
    description: Ollama
    value:
      url: http://localhost:11434
      apiKey: ollama
      models:
        default: phi4

  - key: mux
    public: false
    description: Mux Token ID
    value:
      token:
        id:
          env.variable: MUX_TOKEN_ID
        secret:
          env.variable: MUX_TOKEN_SECRET
      test:
        env.variable: MUX_TEST

  - key: preview.url
    public: false
    description: Preview Content URL
    value:
      value: http://localhost:3000/preview

  - key: qdrant
    public: false
    description: Qdrant
    value:
      host:
        env.variable: QDRANT_HOST
      port:
        env.variable: QDRANT_PORT

  - key: meilisearch
    public: false
    description: Meilisearch
    value:
      host: http://localhost:7701
      apiKey: p8JcB_HuMHRxN7uVXfrG2wU06b5k7oTvaAAYo6nsi9M

