configurations:
  - key: openai
    public: false
    description: OpenAI
    value:
      key:
        env.variable: OPENAI_KEY

  - key: mux
    public: false
    description: Mux Token ID
    value:
      token:
        id:
          env.variable: MUX_TOKEN_ID
        secret:
          env.variable: MUX_TOKEN_SECRET
      test:
        env.variable: MUX_TEST

  - key: sendgrid
    public: false
    description: Sendgrid
    value:
      token:
        env.variable: SENDGRID_API_KEY
      from:
        email: support@sowers.io
        name: Sowers Support

  - key: preview.url
    public: false
    description: Preview Content URL
    value:
      value: http://localhost:3000/preview
