resources:
  - migrations.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: administration-env
    literals:
      - NODE_ENV=production
      - NUXT_GRAPHQL_URL=http://server.bosca.svc.cluster.local:8000/graphql
      - NUXT_GRAPHQL_WS_URL=ws://server.bosca.svc.cluster.local:8000/ws
      - NUXT_PUBLIC_GRAPHQL_URL=https://api.bosca.io/graphql
      - NUXT_PUBLIC_GRAPHQL_WS_URL=wss://api.bosca.io/ws
      - OTLP_TRACE_ENDPOINT=http://otel-collector.bosca.svc.cluster.local:4318/v1/traces
      - OTLP_METRICS_ENDPOINT=http://otel-collector.bosca.svc.cluster.local:4318/v1/metrics
