---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-query
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: analytics-query
  template:
    metadata:
      labels:
        app: analytics-query
    spec:
      containers:
        - name: analytics-query
          image: ghcr.io/sowers-io/bosca/analytics:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
#            limits:
#              memory: "512Mi"
#              cpu: "2"
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8009
              name: http
          env:
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_BUCKET
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ENDPOINT
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: QUERY_AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_BUCKET
            - name: QUERY_AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_QUERY_ENDPOINT
            - name: QUERY_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
            - name: QUERY_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: QUERY_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: QUERY_KEY
          envFrom:
            - configMapRef:
                name: analytics-query-env
      terminationGracePeriodSeconds: 600
      imagePullSecrets:
        - name: packages-credentials