---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ghcr.io/sowers-io/bosca/admin:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
#            limits:
#              memory: "500Mi"
#              cpu: "2"
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 15
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 15
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: BOSCA_SERVER_URL
              value: http://server.bosca.svc.cluster.local:8000/graphql
          envFrom:
            - configMapRef:
                name: admin-env
      terminationGracePeriodSeconds: 180
      imagePullSecrets:
        - name: packages-credentials