id: collection.index.default
name: Index Collection
description: Add Collection to Default Search Index
queue: metadata
activities:
  - queue: metadata
    activity: search.index.item
    configuration:
      storageSystem: Default Search
    inputs:
      - name: supplementary
        supplementary: search.json
