apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrations
  namespace: bosca
spec:
  template:
    spec:
      containers:
        - name: database-content
          image: ghcr.io/sowers-io/bosca/database-migrations:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bosca-database
                  key: connection-string
            - name: DATABASE_URL_CERT_B64
              valueFrom:
                secretKeyRef:
                  name: bosca-database
                  key: certificate
      restartPolicy: Never
      imagePullSecrets:
        - name: packages-credentials