#!/bin/bash

kubectl --kubeconfig config apply -f namespace.yaml
kubectl --kubeconfig config -n bosca delete job database-migrations || true

if [ "$IMAGE_TAG" != "" ]; then
  echo "" >> kustomization.yaml
  echo "images:" >> kustomization.yaml

  echo_image() {
      echo "  - name: $1" >> kustomization.yaml
      echo "    newTag: $2" >> kustomization.yaml
  }

  echo_image "ghcr.io/sowers-io/bosca/database-migrations" $IMAGE_TAG
  echo_image "ghcr.io/sowers-io/bosca/server" $IMAGE_TAG
  echo_image "ghcr.io/sowers-io/bosca/analytics" $IMAGE_TAG
  echo_image "ghcr.io/sowers-io/bosca/kotlin-runner-enterprise-compatibility" $IMAGE_TAG
fi

kubectl kustomize | kubectl --kubeconfig config -n bosca apply -f -

kubectl --kubeconfig config rollout status -n bosca statefulset/analytics-backend
kubectl --kubeconfig config rollout status -n bosca deployment/analytics-frontend
kubectl --kubeconfig config rollout status -n bosca deployment/server
kubectl --kubeconfig config rollout status -n bosca deployment/workflow-server
kubectl --kubeconfig config rollout status -n bosca deployment/runner
kubectl --kubeconfig config rollout status -n bosca deployment/administration