#!/bin/bash

kubectl port-forward --namespace bosca svc/meilisearch 7700:7700 &
kubectl port-forward --namespace bosca svc/ollama 11434:11434 &

sleep 3

curl http://localhost:11434/api/pull -d '{"name": "all-minilm"}'

curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json'  \
  --data-binary '{
    "vectorStore": true
  }'

curl \
  -X POST 'http://localhost:7700/indexes' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "uid": "metadata",
    "primaryKey": "id"
  }'

curl \
  -X PATCH 'http://localhost:7700/indexes/metadata/settings' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "embedders": {
      "default": {
        "source": "ollama",
        "url": "http://ollama.bosca.svc.cluster.local:11434/api/embeddings",
        "model": "all-minilm",
        "documentTemplate": "A document titled {{doc.name}} with a body of {{doc.content|truncatewords:500}}"
      }
    }
  }'

curl \
  -X POST 'http://localhost:7700/indexes' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "uid": "bibleverses",
    "primaryKey": "id"
  }'

curl \
  -X PATCH 'http://localhost:7700/indexes/bibleverses/settings' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "embedders": {
      "default": {
        "source": "ollama",
        "url": "http://ollama.bosca.svc.cluster.local:11434/api/embeddings",
        "model": "all-minilm",
        "documentTemplate": "A Bible verse titled {{doc.name}} with a body of {{doc.content}}"
      }
    }
  }'

curl \
  -X GET 'http://localhost:7700/tasks' \
  -H "Authorization: Bearer $(op item get --vault Services "MeiliSearch" --format json --fields MEILI_MASTER_KEY | jq -r .value)" \
  -H 'Content-Type: application/json'