namespace: bosca

resources:
  - secrets/meilisearch.yaml
  - secrets/s3.yaml
  - secrets/jwt.yaml
  - secrets/serviceaccount.yaml
  - secrets/postgres-bosca.yaml
  - secrets/postgres-bosca-direct.yaml
  - secrets/url-secret.yaml
  - services/otel.yaml
  - services/coroot-pg-agent.yaml
  - cache.yaml
  - notifier-pubsub.yaml
  - server
  - workflow-server
  - analytics-backend
  - analytics-frontend
  - analytics-query
  - meilisearch
  - ollama
  - ingress.yaml
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

