apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: notifier-pubsub
  namespace: bosca
spec:
  env:
    - name: DFLY_lock_on_hashtags
      value: "true"
    - name: DFLY_default_lua_flags
      value: allow-undeclared-keys
    - name: DFLY_cache_mode
      value: "true"
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
