---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: ghcr.io/sowers-io/bosca/kotlin-runner-enterprise:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
          #            limits:
          #              memory: "1024Mi"
          #              cpu: "2"
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: BOSCA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-account
                  key: username
            - name: BOSCA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-account
                  key: password
            - name: MUX_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: mux
                  key: access-token-id
            - name: MUX_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: mux
                  key: secret-key
            - name: RUNPOD_TRANSCRIBE_FUNCTION
              valueFrom:
                secretKeyRef:
                  name: runpod
                  key: function
            - name: RUNPOD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runpod
                  key: token
            - name: RUNPOD_URL
              valueFrom:
                secretKeyRef:
                  name: runpod
                  key: url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: token
          envFrom:
            - configMapRef:
                name: runner-env
          volumeMounts:
            - mountPath: /tmp/bosca
              name: tmp
      volumes:
        - name: tmp
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: runner-tmp
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: 40Gi
      terminationGracePeriodSeconds: 600
      imagePullSecrets:
        - name: packages-credentials