---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-server
  namespace: bosca
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: workflow-server
  template:
    metadata:
      labels:
        app: workflow-server
    spec:
      containers:
        - name: workflow-server
          image: ghcr.io/sowers-io/bosca/server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
#            limits:
#              memory: "1024Mi"
#              cpu: "2"
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_BUCKET
            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ENDPOINT
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bosca-database
                  key: connection-string
            - name: DATABASE_URL_CERT_B64
              valueFrom:
                secretKeyRef:
                  name: bosca-database
                  key: certificate
            - name: DATABASE_JOBS_URL
              valueFrom:
                secretKeyRef:
                  name: boscajobs-database
                  key: connection-string
            - name: DATABASE_JOBS_URL_CERT_B64
              valueFrom:
                secretKeyRef:
                  name: boscajobs-database
                  key: certificate
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: audience
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: issuer
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch
                  key: MEILI_MASTER_KEY
            - name: URL_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: url-secret
                  key: key
            - name: CONFIGURATION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: configuration-secret
                  key: key
          envFrom:
            - configMapRef:
                name: workflow-server-env
      terminationGracePeriodSeconds: 600
      imagePullSecrets:
        - name: packages-credentials