#!/bin/bash

export BOSCA_USERNAME=admin
export BOSCA_PASSWORD=password
export BOSCA_QUEUES="profiles,10;video,4;media,2;default,10;bible,20;bible-ai,10;bible-book,20;bible-chapter,20;bible-verse,10;media-transcription,1;media-upload,5;metadata,50;search-index,100;traits,100;transition,100;"
export BOSCA_URL="http://127.0.0.1:8000/graphql"
export MARCH=compatibility

cd ./workspace/runners/kotlin && ./gradlew nativeBuild

./workspace/runners/kotlin/runner/build/native/nativeCompile/bosca-runner run