#!/bin/bash

cargo build --release

export BOSCA_PASSWORD=password
export BOSCA_QUEUES="bible,20;bible-ai,0;bible-book,20;bible-verse,50;default,50;media-transcription,1;media-upload,5;metadata,50;search-index,100;traits,100;transition,100"
export BOSCA_URL=http://127.0.0.1:8000/graphql
export BOSCA_USERNAME=admin

./target/release/bosca-runner