#!/bin/sh

create_secret() {
name="$1"
namespace="$2"
database_name="$3"
extra_secrets="$4"
database_prefix="$5"

#password="$(kubectl -n $namespace get secret/postgres-pgbouncer -o jsonpath='{.data.pgbouncer-password}' | base64 -d)"
password="$(kubectl -n $namespace get secret/postgres$database_prefix-pguser-$database_name -o jsonpath='{.data.password}' | base64 -d)"
encoded_password="$(jq -rn --arg x "$password" '$x|@uri')"

#url="postgresql://_crunchypgbouncer:$encoded_password@postgres-pgbouncer.$namespace.svc.cluster.local:5432/"
url="postgresql://$database_name:$encoded_password@postgres$database_prefix-pgbouncer.$namespace.svc.cluster.local:5432/"

dsuri="$url$database_name"

kubectl apply -f - <<END
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $name
  namespace: $namespace
data:
  datastore_uri: $(printf '%s' "$dsuri" | base64 -w 0)
  postgres-host: $(printf '%s' "postgres$database_prefix-pgbouncer.$namespace.svc.cluster.local" | base64 -w 0)
  postgres-db: $(printf '%s' "$database_name" | base64 -w 0)
  postgres-username: $(printf '%s' "$database_name" | base64 -w 0)
  postgres-password: $(printf '%s' "$password" | base64 -w 0)
  $extra_secrets
END
}
