---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coroot-pg-agent
  namespace: coroot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: coroot-pg-agent
  template:
    metadata:
      labels:
        app: coroot-pg-agent
    spec:
      containers:
        - name: coroot-pg-agent
          image: ghcr.io/coroot/coroot-pg-agent:latest
          imagePullPolicy: IfNotPresent
          resources: {}
          livenessProbe:
            httpGet:
              port: http
              path: /metrics
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /metrics
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 80
              name: http
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: bosca-database-direct
                  key: dsn
      terminationGracePeriodSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: coroot-pg-agent
  namespace: coroot
spec:
  selector:
    app: coroot-pg-agent
  ports:
    - name: http
      port: 80
