#!/bin/bash

namespace=$1

kubectl -n $namespace create secret docker-registry packages-credentials \
 --docker-server=$(op item get --vault Kubernetes "Kubernetes Docker" --format json --fields url | jq -r .value) \
 --docker-username=$(op item get --vault Kubernetes "Kubernetes Docker" --format json --fields username | jq -r .value) \
 --docker-password=$(op item get --vault Kubernetes "Kubernetes Docker" --format json --fields password | jq -r .value)

#source copy-database-secrets
#
#create_secret "bosca-database" "$namespace" "bosca"
#create_secret "jobs-database" "$namespace" "boscajobs" "" "-jobs"
#