---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: documentation
  template:
    metadata:
      labels:
        app: documentation
    spec:
      containers:
        - name: documentation
          image: ghcr.io/sowers-io/bosca/documentation:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              port: http
              path: /favicon.ico
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: http
              path: /favicon.ico
            initialDelaySeconds: 3
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: documentation-env
      terminationGracePeriodSeconds: 600
      imagePullSecrets:
        - name: packages-credentials