name: Default Search
description: Default Search
type: SEARCH
models: [ ]
configuration:
  type: meilisearch
  indexName: default
  primaryKey: id
  embeddings:
    url: http://ollama:11434/api/embeddings
    model: all-minilm
    source: ollama
    template: A document titled {{doc.name}} with a body of {{doc._content|truncatewords:500}}
  filterable:
    - type
    - _type
    - contentType
    - attributes.type
    - _parents.attributes.type
    - categories.id
  sortable:
    - published
    - modified
  searchable:
    - name
    - attributes.collection
    - categories.name
    - _content
    - _parents.name