name: Build & Publish Documentation

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

env:
  INSTANCE: 'docs/bd'
  DOCKER_VERSION: '243.22562'

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: ${{ github.sha }}
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false
          package_json_file: docs/package.json

      - name: Generate Site
        run: cd docs && pnpm i && pnpm generate

      - name: Build Documentation Image
        uses: docker/build-push-action@v3
        with:
          context: docs
          file: docs/Dockerfile
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/documentation:latest
            ghcr.io/sowers-io/bosca/documentation:${{ github.sha }}
