name: Build & Publish

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - uses: actions/checkout@v3
      - run: cargo clippy

  build-and-publish-backend:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: ${{ github.sha }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - uses: actions/checkout@v3
      - run: cargo build --release
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push database migrations
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-migrations
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/database-migrations:latest
            ghcr.io/sowers-io/bosca/database-migrations:${{ github.sha }}
      - name: Build and push server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-server
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/server:latest
            ghcr.io/sowers-io/bosca/server:${{ github.sha }}
      - name: Build and push runner
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-runner
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/runner:latest
            ghcr.io/sowers-io/bosca/runner:${{ github.sha }}
      - name: Build and push front
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-front
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/front:latest
            ghcr.io/sowers-io/bosca/front:${{ github.sha }}

  build-and-publish-frontend:
    runs-on: ubuntu-22.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_TAG: ${{ github.sha }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push admin
        uses: docker/build-push-action@v3
        with:
          context: workspace/admin
          file: workspace/admin/Dockerfile
          push: true
          tags: |
            ghcr.io/sowers-io/bosca/admin:latest
            ghcr.io/sowers-io/bosca/admin:${{ github.sha }}

  publish-kubernetes:
    runs-on: ubuntu-22.04
    needs:
      - lint
      - build-and-publish-backend
      - build-and-publish-frontend
    env:
      IMAGE_TAG: ${{ github.sha }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      KUBECTL_CONFIG: op://Kubernetes/Kubernetes Config/config
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y kubectl
      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
      - run: cd kubernetes && echo -n $KUBECTL_CONFIG | base64 -d > config
      - run: cd kubernetes && ./deploy
