name: Build & Publish Backend and Frontend

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  build-and-publish-imageprocessor:
    runs-on: ubuntu-22.04
    env:
      RUNNER_TOOL_CACHE: /toolcache
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push imageprocessor
        uses: docker/build-push-action@v3
        with:
          context: workspace/core/imageprocessor
          file: workspace/core/imageprocessor/Dockerfile
          push: true
          tags: |
            ${{ secrets.IMAGE_PREFIX }}/bosca/imageprocessor:latest
            ${{ secrets.IMAGE_PREFIX }}/bosca/imageprocessor:${{ github.sha }}
            ${{ secrets.IMAGE_PREFIX }}/bosca/imageprocessor:${{ github.ref_name }}
