name: Build & Publish Backend and Frontend

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-22.04
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions/checkout@v3
      - run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: export PATH="$HOME/.cargo/bin:$PATH" && cargo clippy

  build-and-publish-backend:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_REGISTRY: ${{ secrets.REGISTRY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions/checkout@v3
      - run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
          unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: export PATH="$HOME/.cargo/bin:$PATH" && cargo build --release
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push database migrations
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-migrations
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/database-migrations:latest
            $IMAGE_PREFIX/bosca/database-migrations:${{ github.sha }}
            $IMAGE_PREFIX/bosca/database-migrations:${{ github.ref_name }}
      - name: Build and push server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-server
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/server:latest
            $IMAGE_PREFIX/bosca/server:${{ github.sha }}
            $IMAGE_PREFIX/bosca/server:${{ github.ref_name }}
      - name: Build and push cache server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-dc
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/cache:latest
            $IMAGE_PREFIX/bosca/cache:${{ github.sha }}
            $IMAGE_PREFIX/bosca/cache:${{ github.ref_name }}
      - name: Build and push analytics
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-analytics
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/analytics:latest
            $IMAGE_PREFIX/bosca/analytics:${{ github.sha }}
            $IMAGE_PREFIX/bosca/analytics:${{ github.ref_name }}

  build-and-publish-runner-community:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
      - run: |
          export JAVA_HOME=/opt/hostedtoolcache/graalvm-community-jdk-24.0.1_linux-x64_bin/24.0.1/x64/graalvm-community-openjdk-24.0.1+9.1
          export PATH=$PATH:$JAVA_HOME/bin
      - run: cd workspace/runners/kotlin && ./gradlew nativeBuild
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-runner
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/kotlin-runner-community:latest
            $IMAGE_PREFIX/bosca/kotlin-runner-community:${{ github.sha }}
            $IMAGE_PREFIX/bosca/kotlin-runner-community:${{ github.ref_name }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-blog-installer
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/blog-installer:latest
            $IMAGE_PREFIX/bosca/blog-installer:${{ github.sha }}
            $IMAGE_PREFIX/bosca/blog-installer:${{ github.ref_name }}

  build-and-publish-runner-community-compatibility:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MARCH: compatibility
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
      - run: |
          export JAVA_HOME=/opt/hostedtoolcache/graalvm-community-jdk-24.0.1_linux-x64_bin/24.0.1/x64/graalvm-community-openjdk-24.0.1+9.1
          export PATH=$PATH:$JAVA_HOME/bin
      - run: cd workspace/runners/kotlin && ./gradlew nativeBuild
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-runner
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/kotlin-runner-community-compatibility:latest
            $IMAGE_PREFIX/bosca/kotlin-runner-community-compatibility:${{ github.sha }}
            $IMAGE_PREFIX/bosca/kotlin-runner-community-compatibility:${{ github.ref_name }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-blog-installer
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/blog-installer-compatibility:latest
            $IMAGE_PREFIX/bosca/blog-installer-compatibility:${{ github.sha }}
            $IMAGE_PREFIX/bosca/blog-installer-compatibility:${{ github.ref_name }}

  build-and-publish-runner-enterprise:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          ssh-key: ${{ secrets.READ_SSH_KEY }}
          token: ${{ secrets.PRIVATE_PAT }}
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
      - run: |
          export JAVA_HOME=/opt/hostedtoolcache/graalvm-community-jdk-24.0.1_linux-x64_bin/24.0.1/x64/graalvm-community-openjdk-24.0.1+9.1
          export PATH=$PATH:$JAVA_HOME/bin
      - run: cd workspace/runners/enterprise/bible && ./gradlew publishToMavenLocal
      - run: cd workspace/runners/kotlin && ./gradlew nativeBuild
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-runner
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise:latest
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise:${{ github.sha }}
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise:${{ github.ref_name }}

  build-and-publish-runner-enterprise-compatibility:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MARCH: compatibility
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          ssh-key: ${{ secrets.READ_SSH_KEY }}
          token: ${{ secrets.PRIVATE_PAT }}
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm-community'
      - run: |
          export JAVA_HOME=/opt/hostedtoolcache/graalvm-community-jdk-24.0.1_linux-x64_bin/24.0.1/x64/graalvm-community-openjdk-24.0.1+9.1
          export PATH=$PATH:$JAVA_HOME/bin
      - run: cd workspace/runners/enterprise/bible && ./gradlew publishToMavenLocal
      - run: cd workspace/runners/kotlin && ./gradlew nativeBuild
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Runner Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-runner
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise-compatibility:latest
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise-compatibility:${{ github.sha }}
            $IMAGE_PREFIX/bosca/kotlin-runner-enterprise-compatibility:${{ github.ref_name }}

  build-and-publish-imageprocessor:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push imageprocessor
        uses: docker/build-push-action@v3
        with:
          context: workspace/core/imageprocessor
          file: workspace/core/imageprocessor/Dockerfile
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/imageprocessor:latest
            $IMAGE_PREFIX/bosca/imageprocessor:${{ github.sha }}
            $IMAGE_PREFIX/bosca/imageprocessor:${{ github.ref_name }}

  build-and-publish-administration:
    runs-on: ubuntu-22.04
    env:
      IMAGE_PREFIX: ${{ secrets.IMAGE_PREFIX }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}
          ssh-key: ${{ secrets.READ_SSH_KEY }}
          token: ${{ secrets.PRIVATE_PAT }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: ./scripts/build-administration
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Publish Administration Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-administration
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/administration:latest
            $IMAGE_PREFIX/bosca/administration:${{ github.sha }}
            $IMAGE_PREFIX/bosca/administration:${{ github.ref_name }}
      - name: Build and Publish Administration Query Installer Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-administration-query-installer
          push: true
          tags: |
            $IMAGE_PREFIX/bosca/administration-query-installer:latest
            $IMAGE_PREFIX/bosca/administration-query-installer:${{ github.sha }}
            $IMAGE_PREFIX/bosca/administration-query-installer:${{ github.ref_name }}
