name: Publish Only

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA'
        required: true

jobs:
  publish-kubernetes:
    runs-on: ubuntu-22.04
    env:
      IMAGE_TAG: ${{ inputs.sha }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      KUBECTL_CONFIG: "op://Kubernetes/Kubernetes Config/config"
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install -y kubectl
      - uses: 1password/load-secrets-action@v2
        with:
          export-env: true
      - run: cd kubernetes && echo -n $KUBECTL_CONFIG | base64 -d > config
      - run: cd kubernetes && ./deploy
